build:
	mvn compile -q
	mvn package -q

lookup:
	mvn exec:java -q -Dexec.mainClass="edu.hse.net.Lookup"

ping:
	mvn exec:java -q -Dexec.mainClass="edu.hse.net.Ping"

serialize:
	mvn exec:java -q -Dexec.mainClass="edu.hse.net.Serialize"

client:
	mvn exec:java -q -Dexec.mainClass="edu.hse.net.Client"

server:
	mvn exec:java -q -Dexec.mainClass="edu.hse.net.Server"
